[project]
name = "semcueca-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.53.0",
]
